module.exports = async function (self) {
	self.setVariableDefinitions([
		{ variableId: 'slide_id', name: 'Holyrics: ID of the current slide' },
		{ variableId: 'slide_type', name: 'Holyrics: Type of the current slide' },
		{ variableId: 'slide_name', name: 'Holyrics: Type of the current slide' },
		{ variableId: 'song_id', name: 'Holyrics: ID of the current song' },
		{ variableId: 'text_id', name: 'Holyrics: ID of the current text' },
		{ variableId: 'reference_id', name: 'Holyrics: Reference ID' },
		{ variableId: 'slide_number', name: 'Holyrics: Number of the current slide' },
		{ variableId: 'slide_count', name: 'Holyrics: Total number of slides' },
		{ variableId: 'show_alert', name: 'Holyrics: Whether an alert is being shown' },
		{ variableId: 'countdown', name: 'Holyrics: Countdown time remaining'},
		{ variableId: 'f8_active', name: 'F8 (wallpaper) active'},
		{ variableId: 'f9_active', name: 'F9 (empty slide) active'},
		{ variableId: 'f10_active', name: 'F10 (black screen) active'},
		{ variableId: 'mp_playing', name: 'MediaPlayer: playing'},
		{ variableId: 'mp_time_elapsed', name: 'MediaPlayer: Elapsed time'},
		{ variableId: 'mp_time_remaining', name: 'MediaPlayer: Remaining time'},
		{ variableId: 'current_lyrics', name: 'ID of the current lyrics from the playlist'},
		{ variableId: 'current_lyrics_title', name: 'Title of the current lyrics from the playlist'},
		{ variableId: 'playlist_first_lyrics', name: 'First lyrics from the playlist'},
		{ variableId: 'playlist_last_lyrics', name: 'Last lyrics from the playlist'},
		{ variableId: 'cp_countdown_show', name: 'Communication Panel: Countdown active'},
		{ variableId: 'cp_countdown_seconds', name: 'Communication Panel: Remaining countdown seconds'},
		{ variableId: 'cp_countdown', name: 'Communication Panel: Countdown time remaining'},
	])
}